/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pfinalp1_cespinal_aieong;

import javax.swing.JButton;
import java.util.Scanner;
import javax.swing.JOptionPane;
public class xo extends javax.swing.JFrame {
Scanner leer=new Scanner(System.in);
    /**
     * Creates new form xo
     */
    public xo() {
        initComponents();
        String opc = JOptionPane.showInputDialog("1<-Player vs Player \n2<-Player vs AI");
        op = Integer.parseInt(opc);
    
        switch(op){
            case 1:
                genmatriz();
                break;
            case 2:
                genmatriz();
                 lol=findBestMove();
                break;
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        boton00 = new javax.swing.JButton();
        boton01 = new javax.swing.JButton();
        boton02 = new javax.swing.JButton();
        boton10 = new javax.swing.JButton();
        boton11 = new javax.swing.JButton();
        boton12 = new javax.swing.JButton();
        boton20 = new javax.swing.JButton();
        boton21 = new javax.swing.JButton();
        boton22 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(204, 0, 0));

        boton00.setText("botton00");
        boton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton00ActionPerformed(evt);
            }
        });

        boton01.setText("botton01");
        boton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton01ActionPerformed(evt);
            }
        });

        boton02.setText("botton02");
        boton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton02ActionPerformed(evt);
            }
        });

        boton10.setText("jButton1");
        boton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton10ActionPerformed(evt);
            }
        });

        boton11.setText("jButton1");
        boton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton11ActionPerformed(evt);
            }
        });

        boton12.setText("jButton1");
        boton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton12ActionPerformed(evt);
            }
        });

        boton20.setText("jButton1");
        boton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton20ActionPerformed(evt);
            }
        });

        boton21.setText("jButton1");
        boton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton21ActionPerformed(evt);
            }
        });

        boton22.setText("jButton1");
        boton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton22ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setText("DMAF's XO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton20, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton21, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boton02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton22, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(boton10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boton00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boton01, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addComponent(boton11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boton21, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(boton02, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boton12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton00ActionPerformed
        if(op==2){
            if(turn%2==0){
                boton00.setText("0");
                boton00.setEnabled(false);
                guin(boton00.getText());
                 lol=findBestMove();
                //turn++;
            }
        }else{
            if(boton00.isEnabled()){
                if(turn%2==0){
                    boton00.setText("X");
                }else{
                    boton00.setText("0");
                }
                turn++;
                boton00.setEnabled(false);
                guin(boton00.getText());
            }else
                JOptionPane.showMessageDialog(null, "Casilla ocuupada");
        }
    }//GEN-LAST:event_boton00ActionPerformed

    private void boton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton01ActionPerformed
        if(op==2){
            if(turn%2==0){
                boton01.setText("0");
                boton01.setEnabled(false);
                guin(boton01.getText());
                 lol=findBestMove();
                //turn++;
                
            }
        }else{
            if(boton01.isEnabled()){
                if(turn%2==0){
                    boton01.setText("X");
                }else{
                    boton01.setText("0");
                }
                turn++;
                boton01.setEnabled(false);
                guin(boton01.getText());

            }else
                JOptionPane.showMessageDialog(null, "Casilla ocuupada");
        }
    }//GEN-LAST:event_boton01ActionPerformed

    private void boton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton02ActionPerformed
        if(op==2){
            if(turn%2==0){
                boton02.setText("0");
                guin(boton02.getText());
                boton02.setEnabled(false);
                 lol=findBestMove();
                //turn++;
                
            }
        }else{
            if(boton02.isEnabled()){
                if(turn%2==0){
                    boton02.setText("X");
                }else{
                    boton02.setText("0");
                }
                turn++;
                boton02.setEnabled(false);
                guin(boton02.getText());
            }else
                JOptionPane.showMessageDialog(null, "Casilla ocuupada");
            }
    }//GEN-LAST:event_boton02ActionPerformed

    private void boton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton10ActionPerformed
        if(op==2){
            if(turn%2==0){
                boton10.setText("0");
                boton10.setEnabled(false);
                guin(boton10.getText());
                 lol=findBestMove();
                //turn++;
                
            }
        }else{
            if(boton10.isEnabled()){
                if(turn%2==0){
                    boton10.setText("X");
                }else{
                    boton10.setText("0");
                }
                turn++;
                boton10.setEnabled(false);
                guin(boton10.getText());
            }else
                JOptionPane.showMessageDialog(null, "Casilla ocuupada");
        }
    }//GEN-LAST:event_boton10ActionPerformed

    private void boton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton11ActionPerformed
        if(op==2){
            if(turn%2==0){
                boton11.setText("0");
                boton11.setEnabled(false);
                guin(boton11.getText());
                 lol=findBestMove();
                //turn++;
                
            }
        }else{
        if(boton11.isEnabled()){
            if(turn%2==0){
                boton11.setText("X");
            }else{
                boton11.setText("0");
            }
            turn++;
            boton11.setEnabled(false);
            guin(boton11.getText());
            }else
                JOptionPane.showMessageDialog(null, "Casilla ocuupada");
        }
    }//GEN-LAST:event_boton11ActionPerformed

    private void boton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton12ActionPerformed
        if(op==2){
            if(turn%2==0){
                boton12.setText("0");
                boton12.setEnabled(false);
                guin(boton12.getText());
                 lol=findBestMove();
               //turn++;
               
            }
        }else{
            if(boton12.isEnabled()){
                if(turn%2==0){
                    boton12.setText("X");
                }else{
                    boton12.setText("0");
                }
                turn++;
                boton12.setEnabled(false);
                guin(boton12.getText());
            }else
                JOptionPane.showMessageDialog(null, "Casilla ocuupada");
        }
    }//GEN-LAST:event_boton12ActionPerformed

    private void boton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton20ActionPerformed
        if(op==2){
            if(turn%2==0){
                boton20.setText("0");
                boton20.setEnabled(false);
                guin(boton20.getText());
                 lol=findBestMove();
                //turn++;
                
            }
        }else{
            if(boton20.isEnabled()){
                if(turn%2==0){
                    boton20.setText("X");
                }else{
                    boton20.setText("0");
                }
                turn++;
                boton20.setEnabled(false);
                guin(boton20.getText());
            }else
                JOptionPane.showMessageDialog(null, "Casilla ocuupada");
        }
    }//GEN-LAST:event_boton20ActionPerformed

    private void boton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton21ActionPerformed
        if(op==2){
            if(turn%2==0){
                boton21.setText("0");
                boton21.setEnabled(false);
                guin(boton21.getText());
                 lol=findBestMove();
                //turn++;
                
            }
        }else{
            if(boton21.isEnabled()){
                if(turn%2==0){
                    boton21.setText("X");
                }else{
                    boton21.setText("0");
                }
                turn++;
                boton21.setEnabled(false);
                guin(boton21.getText());
            }else
                JOptionPane.showMessageDialog(null, "Casilla ocuupada");
        }
    }//GEN-LAST:event_boton21ActionPerformed

    private void boton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton22ActionPerformed
       if(op==2){
            if(turn%2==0){
                boton22.setText("0");
                boton22.setEnabled(false);
                guin(boton22.getText());
                 lol=findBestMove();
                //turn++;
                

            }
        }else{
            if(boton22.isEnabled()){
                if(turn%2==0){
                    boton22.setText("X");
                }else{
                    boton22.setText("0");
                }
                turn++;
                boton22.setEnabled(false);
                guin(boton22.getText());
            }else
                JOptionPane.showMessageDialog(null, "Casilla ocuupada");
       }
    }//GEN-LAST:event_boton22ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       genmatriz();
        if(op==2){
            Move lol=findBestMove();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public JButton[][]tablero=new JButton[3][3];
    int turn=0,line,col;
    int colu,lin,op,depth=0;
    Move lol;
    //public JButton [][]bestmove=new JButton[3][3];
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xo().setVisible(true);
            }
        });
    }
    public void genmatriz(){
        turn=0;
        tablero[0][0]=boton00;
        tablero[0][1]=boton01;
        tablero[0][2]=boton02;
        tablero[1][0]=boton10;
        tablero[1][1]=boton11;
        tablero[1][2]=boton12;
        tablero[2][0]=boton20;
        tablero[2][1]=boton21;
        tablero[2][2]=boton22;
        
        for (int i = 0; i < tablero.length; i++) {
            for (int j = 0; j < tablero.length; j++) {
                tablero[i][j].setText("[ ]");
                tablero[i][j].setEnabled(true);
            }
        }
    }
    
    public void guin(String player){
        int uno=0,dos=0,tres=0,cuatro=0,space=0;
        for (int i = 0; i <tablero.length; i++) {
            for (int j = 0; j < tablero[i].length; j++) {
                if(i == j ){
                    if (tablero[i][j].getText().equals(player)){
                        uno++;
                    }
                }
                if(i+j==tablero.length-1){
                    if (tablero[i][j].getText().equals(player)){
                        dos++;
                        
                    }
                }
                   
            }
        }
        for (int i = 0; i <tablero.length; i++) {
            for (int j = 0; j < tablero[i].length; j++) {
                if (tablero[i][j].getText().equals(player)){
                        tres++;
                }
            }
            if(tres==3){
                break;
            }else
                tres=0;
        }
        for (int i = 0; i <tablero.length; i++) {
            for (int j = 0; j < tablero[i].length; j++) {
                if (tablero[j][i].getText().equals(player)){
                        cuatro++;
                }
            }
            if(cuatro==3){
                break;
            }else
                cuatro=0;
            
        }
        for (int i = 0; i <tablero.length; i++) {
            for (int j = 0; j < tablero.length; j++) {
                if(tablero[i][j].getText().equals("[ ]")){
                    space++;
                }
            }
        }
        if(uno==3||dos==3||tres==3||cuatro==3){
            JOptionPane.showMessageDialog(null, player+" Ha ganado");
            genmatriz();
            if(op==2){
            Move lol=findBestMove();
        }
        }else
            if(space==0){
                JOptionPane.showMessageDialog(null, "Empate");
                genmatriz();
                if(op==2){
                    Move lol=findBestMove();
                }
            }
        
    }
    
     class Move{
        int row,colu;
    }
     
    Move findBestMove(){
    int bestVal = -1000;
    Move bestMove = new Move();
    bestMove.row = 0;
    bestMove.colu = 0;
  
    
    for (int i = 0; i < 3; i++){
        for (int j = 0; j < 3; j++){
            if (tablero[i][j].getText().equals( "[ ]")){
                tablero[i][j].setText( "X");
 
                int moveVal = minimax (0, false);
  

                tablero[i][j].setText("[ ]");
  
                if (moveVal > bestVal){
                    bestMove.row = i;
                    bestMove.colu = j;
                    bestVal = moveVal;
                    tablero[bestMove.row][bestMove.colu].setText("X");
                    tablero[bestMove.row][bestMove.colu].setEnabled(false);
                    guin(tablero[i][j].getText());
                }
            }
        }
    }
    return bestMove;
    }
    
     int minimax(int depth, Boolean isMax){
    int score = evaluate();
   
    if (score == 10)
        return score;
   
    if (score == -10)
        return score;
   
    if (isMovesLeft() == false)
        return 0;
    if (isMax==true){
        int best = -1000;
        
        for (int i = 0; i < 3; i++){
            for (int j = 0; j < 3; j++){
                
                if (tablero[i][j].getText().equals( "[ ]")){
          
                    tablero[i][j].setText("X");
                    best = Math.max(best, minimax(depth + 1, false));
                    tablero[i][j].setText("[ ]");
                }
            }
        }
        return best;
    }
  
   
    else{
        int best = 1000;
      
        for (int i = 0; i < 3; i++){
            for (int j = 0; j < 3; j++){
                
                if (tablero[i][j].getText().equals("[ ]")){
                 
                    tablero[i][j].setText("0");
                    
                    best = Math.min(best, minimax(depth + 1, true));
                   
                    tablero[i][j].setText("[ ]");
                }
            }
        }
        return best;
    }
}
     
    int evaluate(){
    for (int row = 0; row < 3; row++){
        if (tablero[row][0] == tablero[row][1] &&tablero[row][1] == tablero[row][2]){
            if (tablero[row][0].getText().equals( "X"))
                return +10;
            else if (tablero[row][0].getText().equals("0"))
                return -10;
        }
    }
  
   
    for (int col = 0; col < 3; col++){
        if (tablero[0][col] == tablero[1][col] &&
            tablero[1][col] == tablero[2][col]){
            if (tablero[0][col].getText().equals("X"))
                return +10;
  
            else if (tablero[0][col].getText().equals( "0"))
                return -10;
        }
    }
  
    
    if (tablero[0][0] == tablero[1][1] && tablero[1][1] == tablero[2][2]){
        if (tablero[0][0].getText().equals("X"))
            return +10;
        else if (tablero[0][0].getText().equals("0"))
            return -10;
    }
  
    if (tablero[0][2] == tablero[1][1] && tablero[1][1] == tablero[2][0]){
        if (tablero[0][0].getText().equals("X"))
            return +10;
        else if (tablero[0][0].getText().equals("0"))
            return -10;
    }
    
    return 0;
}
    
    Boolean isMovesLeft(){
    for (int i = 0; i < 3; i++)
        for (int j = 0; j < 3; j++)
            if (tablero[i][j].getText().equals("[ ]"))
                return true;
    return false;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton00;
    private javax.swing.JButton boton01;
    private javax.swing.JButton boton02;
    private javax.swing.JButton boton10;
    private javax.swing.JButton boton11;
    private javax.swing.JButton boton12;
    private javax.swing.JButton boton20;
    private javax.swing.JButton boton21;
    private javax.swing.JButton boton22;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
